### ISSUE TITLE
backport of features to 3.y.z versions

### ISSUE THREAD

**Issue by AndrewAnnex** [developmentseed/morecantile#116]
for https://github.com/developmentseed/cogeo-mosaic/pull/210, I would like to update the pr to use the changes from #109 and #111 but cogeo-mosaic pins to versions of morecantile older than 4.0.0. Maybe the changes for tms 2.0 aren't too disruptive and cogeo-mosaic can be updated to use the alpha release, but a backport 3.3.1 or 3.4.0 release with these changes and any others that have occurred since 3.3.0 would be preferable for now I think to make the upgrade path smoother for other projects currently using 3.3.0 morecantile.

**Comment by vincentsarago** [comment]
https://pypi.org/project/morecantile/3.4.0/

done
