### ISSUE TITLE
Custom Tileset can't be set

### ISSUE THREAD

**Issue by cirquelar** [developmentseed/morecantile#22]
I'm trying to create a custom tile matrix based on the example:
> import rasterio, morecantile
> from rasterio.crs import CRS
> crs = CRS.from_proj4("+proj=stere +lat_0=90 +lon_0=0 +k=2 +x_0=0 +y_0=0 +R=3396190 +units=m +no_defs")
> extent = [-13584760.000,-13585240.000,13585240.000,13584760.000]
> tms = morecantile.TileMatrixSet.custom(extent, crs, indentifier="MarsNPolek2MOLA5k")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: custom() got an unexpected keyword argument 'indentifier'

if I remove 'indentifier':
> tms = morecantile.TileMatrixSet.custom(extent, crs, "MarsNPolek2MOLA5k")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/fcalef/miniconda3/envs/py37/lib/python3.7/site-packages/morecantile/models.py", line 157, in custom
    width / (tile_width * matrix_scale[0]) / 2.0 ** zoom,
TypeError: unsupported operand type(s) for /: 'float' and 'str'

I don't see any obvious syntax mistakes.

**Comment by vincentsarago** [comment]
Hi @cirquelar thanks for opening the issue. 

There is a typo in the doc 🤦 it's not `indentifier` but `identifier`. Sorry about that 

```python
import rasterio
import morecantile 
from rasterio.crs import CRS 

crs = CRS.from_proj4("+proj=stere +lat_0=90 +lon_0=0 +k=2 +x_0=0 +y_0=0 +R=3396190 +units=m +no_defs") 
extent = [-13584760.000,-13585240.000,13585240.000,13584760.000] 
tms = morecantile.TileMatrixSet.custom(extent, crs, identifier="MarsNPolek2MOLA5k")  
```

I'll fix the Readme 🙏

**Comment by vincentsarago** [comment]
👋 also noting that in Morecantile the CRS uses epsg number for CRS representation and thus you maybe encounter some problems with your CRS.

**Comment by cirquelar** [comment]
The spelling fix worked, thanks!

> CRS uses epsg number for CRS representation and thus you maybe encounter some
> problems with your CRS.
since I'm working with a custom projection with a non-Earth radius, do I have to make a fake EPSG number?

**Comment by vincentsarago** [comment]
> since I'm working with a custom projection with a non-Earth radius, do I have to make a fake EPSG number?

Well sadly you can't do this. I'll see if when creating a custom TMS we can keep the CRS definition (I'll open a separate issue). 

FYI: TMS specification mention that `supported‌CRS` must be an URI type, and gdal/rasterio are able to parse those to create the CRS object internaly (e.g `rasterio.crs.CRS.from_user_input("http://www.opengis.net/def/crs/EPSG/0/3978")`
