### ISSUE TITLE
Custom CRS

### ISSUE THREAD

**Issue by vincentsarago** [developmentseed/morecantile#23]
in #22 an user wanted to used a custom CRS defined from a proj4 string 

```python
import morecantile 
from rasterio.crs import CRS 

crs = CRS.from_proj4("+proj=stere +lat_0=90 +lon_0=0 +k=2 +x_0=0 +y_0=0 +R=3396190 +units=m +no_defs") 
extent = [-13584760.000,-13585240.000,13585240.000,13584760.000] 
tms = morecantile.TileMatrixSet.custom(extent, crs, identifier="MarsNPolek2MOLA5k")  
```

While the TMS creation works, the internal representation of the CRS won't work because morecantile is trying to create an URI type 

```python
tms.supportedCRS                                                                                                                         
>  'http://www.opengis.net/def/crs/EPSG/0/None'
```

Because 

```python
crs = CRS.from_proj4("+proj=stere +lat_0=90 +lon_0=0 +k=2 +x_0=0 +y_0=0 +R=3396190 +units=m +no_defs") 
crs.to_epsg()
> None
```

I think we should default the `tms.crs` to the custom one instead of doing 
`inputCRS -> toEPSG -> toURI -> toCRS`

cc @cirquelar

**Comment by cirquelar** [comment]
Is this change to how `tms.crs` being introduced? Can you direct me towards the code that handles this?

**Comment by vincentsarago** [comment]
👋 @cirquelar in https://github.com/developmentseed/morecantile/pull/27 I fixed this issue but sadly we need to wait for `rasterio==1.2.0` to be release because this PR use new rasterio functionality. 

If you want to test you will have to compile rasterio master branch.

**Comment by cirquelar** [comment]
Great! At least I know the functionality will be there in the (near-ish) future.

**Comment by vincentsarago** [comment]
done in #27 

will be include in morecantile==1.3.0
