### ISSUE TITLE
Custom UTM TileMatrixSets

### ISSUE THREAD

**Issue by aliasmrchips** [developmentseed/morecantile#45]
How does one create custom TMS for UTM zones? I am not sure what to use for the extent.

I am confused because the bounds in the example UTM31WGS84Quad do not match the bounds listed here:

https://epsg.io/32631

I guess that json file is derived from the opengis examples?

http://schemas.opengis.net/tms/1.0/xml/examples/UTM31WGS84Quad.xml

What am I missing?

**Comment by vincentsarago** [comment]
Hi @aliasmrchips 

you can totally define your own grid as described in https://developmentseed.org/morecantile/usage/#define-custom-grid

> I am confused because the bounds in the example UTM31WGS84Quad do not match the bounds listed here:

Yep the grid come from the examples, I didn't check the value in it, trusting OGC ;-) 

I also found that Projection bounds can vary from one source to another!

**Comment by vincentsarago** [comment]
@aliasmrchips I'm going to close this, feel free to re-open if ☝️ did not make sense
