### ISSUE TITLE
add `NZTM2000Quad`

### ISSUE THREAD

**Issue by vincentsarago** [developmentseed/morecantile#46]
https://github.com/linz/NZTM2000TileMatrixSet

cc @blacha

**Comment by blacha** [comment]
Cool, I can make a pull request here when we move the tile matrix out of "Preview", we are doing bit of customer testing with it to make sure it works with a bunch of different ArcGIS setups, It works fine in QGIS ;)

**Comment by vincentsarago** [comment]
done in #57
