### ISSUE TITLE
Non-Earth TMS definitions

### ISSUE THREAD

**Issue by davenquinn** [developmentseed/morecantile#67]
I'm trying to use this library to create TileMatrixSet definitions (ultimately for `cogeo-mosaic`, `titiler` and friends) for non-Earth (Mars) coordinate reference systems. Most aspects of the math are exactly the same, but recent Proj has gotten strict about ellipsoids. This is a good thing for most users, but the "Cannot find coordinate operations from 'EPSG:4326' to XXX" has become a source of dread for planetary scientists ;)

I've been able to successfully adapt the `TileMatrixSet` definition to mostly work for the "Mars 2000" CRS, but I had to reimplement more than I ideally would to simply change the CRS:

```python

MARS2000_SPHERE = CRS.from_dict(
    {"proj": "longlat", "R": 3396190, "no_defs": True}
)

class MarsTMS(TileMatrixSet):
    _to_mars2000 = PrivateAttr()
    _from_mars2000 = PrivateAttr()

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)

        # Mars 2000 sphere can be used because lat/lon are defined
        # as planetocentric on Mars
        self._to_mars2000 = Transformer.from_crs(
            self.supportedCRS, MARS2000_SPHERE, always_xy=True
        )
        self._from_mars2000 = Transformer.from_crs(
            MARS2000_SPHERE, self.supportedCRS, always_xy=True
        )

    @property
    def bbox(self):
        """Return TMS bounding box in WGS84."""
        bbox = self._to_mars2000.transform_bounds(*self.xy_bbox, densify_pts=21)
        return BoundingBox(*bbox)

    def xy(self, lng: float, lat: float, truncate=False) -> Coords:
        """Transform longitude and latitude coordinates to TMS CRS."""
        if truncate:
            lng, lat = truncate_lnglat(lng, lat)

        inside = point_in_bbox(Coords(lng, lat), self.bbox)
        if not inside:
            warnings.warn(
                f"Point ({lng}, {lat}) is outside TMS bounds {list(self.bbox)}.",
                PointOutsideTMSBounds,
            )

        x, y = self._from_mars2000.transform(lng, lat)

        return Coords(x, y)
```

The lengthy redefinition is needed to replace the `_to_wgs84` and `_from_wgs84` definitions. Ideally, these could be replaced by `_to_geographic` and `_from_geographic` methods, with the geographic coordinate system being user-supplied (WGS84 by default). This could also help with other planets and other reasons people might define a custom ellipsoid.

If you think I'm missing a simpler way to achieve this, please let me know. If not, I'm happy to supply a PR.

**Comment by vincentsarago** [comment]
@davenquinn I agree this is not perfect I need to think a bit more about this. 

I think renaming the private attribute does make a lot of sense. We then could add another attribute called `geographic_crs` which default to `wgs84` but let you specify `MARS2000_SPHERE`

**Comment by vincentsarago** [comment]
@davenquinn could you provide a non geographic TMS for Mars? (so I can test the transformation between it and the MARS2000 crs

**Comment by vincentsarago** [comment]
@davenquinn I've pushed some changes in https://github.com/developmentseed/morecantile/pull/68, it would be really kind of you if you could test the proposed solution.

```python
from pyproj import CRS
from morecantile import TileMatrixSet

tms = TileMatrixSet.custom(extent=, crs=, geographic_crs= MARS2000_SPHERE)
```
```

**Comment by vincentsarago** [comment]
ping @davenquinn
